- src/ontology/ro-edit.owl
See #103 
output from shahim's git diff:
```
gitowl ||  subject: NO_SUBJECT 
gitowl --  SubObjectPropertyOf(ObjectPropertyChain(obo:RO_0002211 obo:BFO_0000050) obo:RO_0002211)
gitowl ||      regulates o BFO_0000050 SubPropertyOf regulates
```
@dosumis can you +1 or merge this PR?
> Regulates property chain fixes

- src/ontology/Makefile
- src/ontology/subsets/ro-chado.obo
- src/tools/translate-to-chado-obo.pl
> DO NOT MERGE YET First pass at #68 making a ro-chado subset

- src/ontology/ro-edit.owl
It would be convenient to have the inverses of the two relations from #105.
Potential problem: As defined here, these forward and inverse versions use the same parent 'causes or contributes to condition'. Maybe the inverses need a different parent.
> First pass at inverse immune relations, #105

- subsets/ro-chado.obo
As discussed in erasche/docker-tripal#6, we have a problem loading ro-chado.obo in chado.
It looks like removing "OBO_REL:is_a" from ro-chado fixes the problem.
> Remove is_a from ro-chado.obo

- src/ontology/ro-edit.owl
```
gitowl
gitowl ||  Diffing:  src/ontology/ro-edit.owl
gitowl ||
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0002494
gitowl --  SubObjectPropertyOf(obo:RO_0002494 obo:BFO_0000062)
gitowl ||      transformation of SubPropertyOf BFO_0000062
gitowl ||
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0002495
gitowl --  SubObjectPropertyOf(obo:RO_0002495 obo:RO_0002087)
gitowl ||      immediate transformation of SubPropertyOf RO_0002087
gitowl
```
> Removed transformation of subPropertyOf preceded_by. Fixes #126

- src/ontology/ro-edit.owl
In response to the discussion on 1bb0e22d1a554addd652e02eaa3e45fd77a78b64, I created three SWRL rules:
```
enables(?x, ?y), 'occurs in'(?y, ?z) -> 'part of'(?x, ?z)
'negatively regulates'(?x, ?y), 'positively regulates'(?y, ?z) -> 'negatively regulates'(?x, ?z)
'positively regulates'(?x, ?y), 'negatively regulates'(?y, ?z) -> 'negatively regulates'(?x, ?z)
```
This should make the file valid OWL DL. I also removed the property chain version of these.
> Moved problematic property chains to SWRL rules.

- src/ontology/ro-edit.owl
I got sick of trying to justify the old, frankly unreadable definitions on the regulates relations.  This pull request replaces these old definitions with ones I presented to GO in LA in November 2016.  I just reviewed them with the causal relations working group and all agreed to the change.  Note that we deliberately removed the clause 'x is the realization of a function to exert an effect on' and have not replaced it with anything equivalent.  IIRC, this clause was meant to restrict use of the relation to  processes that realize canonical, 'evolved' regulatory functions.   We think that a more general relation is needed for integration purposes and that such restrictions should be imposed when the relations are used, if (as in GO curation or the GO ontology) it is appropriate to do so.
> New, more readable relation definitions for regulates relations in RO

- src/ontology/ro-edit.owl
Removes `'enabled by' SubPropertyOf inverse('capable of')` and fixes #242. I believe this axiom is redundant anyway, since we have:
- `'enabled by' InverseOf 'enables'`
- `'enables' SubPropertyOf 'capable of'`
> Remove inverse expression superproperty for ‘enabled by’.

- src/ontology/ro-edit.owl
This was used to group causal relations and correlative relations.
The grouping was somewhat arbitrary and very poorly defined.
For now we should not group these two sets of relations
Fixes #235
> Obsoleted "related via dependence to"

- src/ontology/ro-edit.owl
> Correct ‘directly develops from’ definition error.

- src/ontology/rohom.owl
`rohom.owl` contains an invalid URL to a Wikipedia cross-reference, that ends up in `ro.obo` when building the ontology.
> Fix wikipedia URL in `rohom.owl`

- src/ontology/ro-edit.owl
> Remove incorrect domain from 'relation between physical entity and a process or stage'.

- src/ontology/ro-edit.owl
Fixes #489 
This property is a "fake" OP that is used for cases in which `has participant` has a cardinality constraint. 
This ticket arose out of issues in ENVO. See ENVO tickets:  
https://github.com/EnvironmentOntology/envo/issues/1182   
https://github.com/EnvironmentOntology/envo/issues/1072
@cmungall I used your id range.
> add "has component participant" object property

- src/ontology/ro-edit.owl
- src/ontology/ro-idranges.owl
Fixes #497 
Added the `utilizes` relation, which is defined as:
```
X utilizes Y means X and Y are material entities, and X is capable of some process P that has input Y.
```
I also performed some other clean up on the `has component participant` relation that I add a bit ago.
@linikujp Can you please review the definition and usage example.
> Issue 497: add utilizes relation

- src/ontology/core.owl
http://purl.org/dc/elements/1.1/license to http://purl.org/dc/terms/license
Fixes #536
> Fix dc:license 

- src/ontology/Makefile
fixes #140 
DO NOT MERGE BEFORE
> Adds domain and range reasoning to ro.owl

- src/ontology/ro-edit.owl
Fixes error noted by @dosumis on CL/hubmap call This fix brings us into alignment with https://github.com/obophenotype/uberon/wiki/Branching-structures-Design-Pattern
See also https://github.com/obophenotype/uberon/issues/2212
> Fixes for branching structures

- src/ontology/ro-edit.owl
Fixes #547 
Removed the `ro.owl` part from the IRI for `utilizes`. The IRI is now:  
http://purl.obolibrary.org/obo/RO_0017001
> fix IRI for utilizes

- src/ontology/ro-edit.owl
The `never_in_taxon` (RO_0002161) macro expands to an invalid syntax that is not recognized and therefore ignored by owltools --expand-macros.
This patch fixes the expansion to use a valid Manchester syntax as expected by owltools.
closes #546
> Fix expansion of never_in_taxon to use correct syntax.

- src/ontology/core.owl
on the old bearer of relation (since deprecated).
This is flagged by the OBO dashboard report.
> Remove deprecated inverse assertion

- src/ontology/ro-edit.owl
see https://github.com/pato-ontology/pato/issues/454
Note: `has relative magnitude` does not have a definition in PATO so might need to write one up here
> Moving PATO OP to RO

- src/ontology/ro-edit.owl
Required for OBO-Edit OBO parser.
Related to #511.
> Fix datetime format for recently added term. 

- src/ontology/ro-edit.owl
fix #580 
I tried looking very far back in time, and I cannot find any evidence of overlaps ever being symmetric..
Is there any ontology that has plenty of overlaps relations to test this with?
cc @dosumis who I think uses overlaps a lot
> Make overlaps symmetric

- src/patterns/ro-interaction-relations-src.yaml
- src/patterns/ro-interaction-relations.ofn
- src/patterns/ro-interaction-relations.owl
- src/patterns/ro-metamodel.yaml
This PR fixes the casing in one instance of `OIO` and reruns make. For some reason there were extra zeros in the IAO local ids
> Clean up ro-metamodel.yaml

- src/ontology/ro-edit.owl
Adding "surface of" as alternative to "2D boundary of".
This is to support https://github.com/oborel/obo-relations/issues/509
> Adding "surface of" alt label

- src/ontology/ro-edit.owl
Remove axiom `drains only 'connected anatomical structure'` asserted for [CARO:0000006 'material anatomical entity'](https://www.ebi.ac.uk/ols/ontologies/caro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0000006)).
If applied, this commit will fix #623.
> Remove axiom

- src/ontology/ro-edit.owl
Closes #371
For ChIRO and the Chemical Roles Graph (https://github.com/chemical-roles/chemical-roles), we need more detailed relationships to describe causal interactions between chemicals (material entities) and receptors (material entity).
Existing relationships (i.e., [directly negatively regulates activity of](http://purl.obolibrary.org/obo/RO_0002449) and [directly positively regulates activity of](http://purl.obolibrary.org/obo/RO_0002450)) are not detailed enough.
See similar issue about drug-target relationships in https://github.com/oborel/obo-relations/issues/144.
This PR creates 3 new properties:
| LUID | Name | Parent | Example |
|----------:|-------|--------|-------|
| 0018027 |  is agonist of | [directly positively regulates activity …
> NTR: Add 3 pharmacological relations for small molecules

- src/ontology/ro-edit.owl
see https://github.com/obophenotype/uberon/issues/2749
relation: 'developmentally induced by'
> Relax range and domain on RO:0002256

- src/ontology/ro-edit.owl
The 'has soma location' (RO:0002100) should not have a range restriction to CARO's 'connected anatomical structure' (CARO:0000003), but rather to 'material anatomical entity' (CARO:0000006), which does not state anything about the "connectedness" of the entity that a neuron's soma may be located in.
closes #702
> Relax the range restriction on 'has soma location'.

- src/ontology/ro-edit.owl
Closes #697 
This PR adds five new relationships corresponding to relationships in the ChEBI ontology as a follow-up to #662, where we added two relationships from ChEBI related to conjugate acids and bases.
| Identifier | Label | Description | ChEBI |
|-----------|--------|------------|------|
| RO:0018038 | has functional parent | Chemical A has functional parent Chemical B if there is chemical transformation through which chemical B can be produced from chemical A. <br><br> For example, the relationship between a salt and a freebased compound is a "has functional parent" relationship. | http://purl.obolibrary.org/obo/chebi#has_functional_parent |
| RO:0018040 | has parent hydride | Chemical A has parent hydride Chemical B if there exists a molecular graphical transformation where …
> Add remaining 5 ChEBI relations

- src/ontology/ro-edit.owl
Suggested in https://github.com/oborel/obo-relations/pull/728#discussion_r1238352410, this PR switches the chemical relationships I've recently added to use skos:exactMatch instead of oio:hasDbXref.
> Update chemical relation xrefs to skos:exactMatch

- src/ontology/ro-idranges.owl
@ddooley your ids range is:
```
Datatype: idrange:25
Annotations: allocatedto: "Damion Dooley"
EquivalentTo: xsd:integer[> 17500 , <= 18000]
```
We need approval from @anitacaron and one other (I think).
> assign id ranges to Damion Dooley

- .github/workflows/stale-issues-and-prs.yml
I wondered why issue #530 was closed as not having seen any activity in 2 years when it hadn't been 2 years. This is why: this workflow had
>  days-before-issue-stale: 630
when it should be 730.
> Correct number of days in 2 years (730, not 630)

- src/ontology/ro-edit.owl
This corrects an inadvertent change within #761.
> Restore parent of 'regulates in another organism' to be 'causally upstream of or within'.

- src/ontology/ro-edit.owl
Discussion in https://github.com/oborel/obo-relations/pull/742 led to understanding that "in taxon" allows both organism and process/life stage assignment to organism taxon.  The "life cycle stage of" synonymy allows "in taxon" to be found for life cycle association.
> Narrow synonym arising from pull 742 discussion

- .github/workflows/diff.yml
- src/ontology/ro-edit.owl
Fixes #769
The same workflow (with modification) is used in CL and Uberon.
> GitHub Action to post `ro-edit.owl` diff

- src/ontology/ro.Makefile
Based on the comment in the diff
> # TODO: This goal (and tmp/missing-base.owl) can be removed once https://github.com/ontodev/robot/issues/1108 is resolved
It is now possible to remove this
close #794
> Remove base overwrite in RO
