oborel/obo-relations

- src/ontology/ro-edit.owl
Added causation properties between genetic variants or environments and conditions as per oborel/obo-relations#91
> Adding causal variant-condition relations

- src/ontology/ro-edit.owl
Using RO_0001020 and RO_0001021, which aren't in the idranges file. Happy to change these.
> Add allergy and autoimmune trigger relations, see #105

- src/tools/translate-to-chado-obo.pl
- subsets/ro-chado.obo
Taking another whack at  this:
https://github.com/oborel/obo-relations/pull/116
@cmungall: how about this?
> changing default namespace from "ro" to "relationship"

- src/ontology/ro-edit.owl
> Fixed AnnotationProperty/ObjectProperty illegal punning

- src/ontology/ro-edit.owl
I added some terms I need for my globi files. The changes are in ro-edit.owl
> added new terms

- src/ontology/Makefile
- src/ontology/catalog-v001.xml
- src/ontology/go_cc_import.owl
- src/ontology/ro-edit.owl
> Separating out GO CC imports

- src/ontology/ro-edit.owl
NRR: 'has exposure stimulus', fixes #172
```
gitowl ||  Diffing:  src/ontology/ro-edit.owl
gitowl ||
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0002241
gitowl --  SubObjectPropertyOf(obo:RO_0002241 obo:RO_0002244)
gitowl ||      has exposure stressor SubPropertyOf related via exposure to
gitowl ++  SubObjectPropertyOf(obo:RO_0002241 obo:RO_0002309)
gitowl ||      has exposure stressor SubPropertyOf has exposure stimulus
gitowl ||
gitowl ||  subject: http://purl.obolibrary.org/obo/RO_0002309
gitowl ++  SubObjectPropertyOf(obo:RO_0002309 obo:RO_0002244)
gitowl ||      has exposure stimulus SubPropertyOf related via exposure to
gitowl ++  AnnotationAssertion(dc:contributor obo:RO_0002309 "Chris Mungall")
gitowl ||      <http://purl.obolibrary.org/obo/RO_0002309> contributor "Chris …
```
> WIP: exposure relations

- src/ontology/ro-edit.owl
Addressed term requests from DAF spec developers as discussed in #149.
- added 'exacerbates condition', 'condition exacerbated by', 'condition ameliorated by' properties
- changed label of 'is preventative for condition' to 'ameliorates condition'.
- also made minor updates to text of definitions for causes or contributes to condition relations, as noted in comment [here](https://github.com/oborel/obo-relations/issues/149#issue-205015473).
> Added relations requested for DAF spec in #149

- src/ontology/ro-edit.owl
Hiya,
I'd like to get these rules for GO-CAM inference in place ASAP.  Please could you take a quick look?
Cheers,
David
> Fixes #180

- src/ontology/ro-edit.owl
to be consistent with def of direct process:process reg branch
* Updated molecularly interacts with to also fit consistent definition of direct.
* Added agonist and antagonist relations
> * Updated definitions of reg relations between material entities

- src/ontology/ro-edit.owl
See refactoring doc for details: https://docs.google.com/document/d/18VQaVHvTmNvJuRczlnmJnjLtd2WxvfGafXoU1LFEQ2c
CC @vanaukenk
> More rules for GOCAM. 

- src/ontology/ro-edit.owl
See https://jbiomedsem.biomedcentral.com/articles/10.1186/2041-1480-4-30
See also FlyBase/flybase-controlled-vocabulary#5
> Data property used to record increases in age-specific mortality rate

- generated-axioms.owl
- src/ontology/Makefile
- src/ontology/catalog-v001.xml
- src/ontology/generated-axioms.owl
- src/ontology/ro-edit.owl
- src/ontology/ro.owl
- src/ontology/sparql/construct-universal-from-homeomorphy.sparql
Added homeomorphy declarations for part-of and in-similarity-relation-with, see #164
> Ready to merge: homemorphy meta-relations see #164

- src/ontology/ro-edit.owl
- Added some irreflexive characteristics
- Additional property chains
- Additional curator notes on some properties
> Ready to merge: Additional axiomatization on existing relations

- src/ontology/other_import.owl
> READY TO MERGE: Removing annotation property assertion on is-about

- src/ontology/ro-edit.owl
> edit 'is model of' label and definition

- src/ontology/ro-edit.owl
> Update ro-edit to include overlaps o part of chain

- src/ontology/ro-edit.owl
> Subproperties of 'has synaptic terminal in'

- README.md
> Added "how to cite"

- src/ontology/ro-edit.owl
This aligns the range with the `disease has location`. For more discussion see:
https://github.com/monarch-initiative/mondo/issues/2180
> Change range of 'disease has inflammation site' to allow immaterial entities

- src/ontology/ro-idranges.owl
related to https://github.com/oborel/obo-relations/issues/419#issuecomment-761122111
> add unused id range for Jorrit Poelen as suggested by @cmungall

- docs/ro-core.md
> Update core docs to reflect changes in inheres in / characteristic of

- src/ontology/ro-edit.owl
> Fixing wrong annotation relations

- src/ontology/ro-edit.owl
> Updated the definition for RO:0004030 (disease arises from structure)

- src/ontology/go-biotic.owl
- src/ontology/ro-edit.owl
> 'Removeing stale GO classes fixes #474

- docs/changes-since-2005-paper.md
- docs/ro-and-bfo.md
- mkdocs.yml
> google analytics

- src/ontology/ro-edit.owl
> fix misspelling in 'occurrent part of'

- src/ontology/ro-edit.owl
> updated label name to 'disease arises from alteration in structure'

- CONTRIBUTING.md
> Added info about mailing list and meetings

- README.md
> added "How to contribute to RO and join the RO working group"

- src/ontology/ro-edit.owl
> Add SPARQL expansion for 'mutually spatially disjoint with’.

- src/ontology/ro-edit.owl
Relies on annotation property added by #615; merge that one first.
> Add SPARQL expansions for 'never in taxon' and 'present in taxon'

- src/ontology/ro-edit.owl
> Causal relation refactor

- src/ontology/ro-edit.owl
Change the range of RO to be anatomical entity instead 
Related to https://github.com/obophenotype/cell-ontology/issues/1782 (see CL ticket for reason)
Thanks to @gouttegd & @bvarner-ebi
> Relax the Range on RO_0002295

- annotations.owl
> Restoring annotations.owl module but in deprecated state

- src/ontology/Makefile
- src/ontology/imports/omo_import.owl
- src/ontology/ro-odk.yaml
- src/ontology/ro.Makefile
@wdduncan thanks for noticing.. I never did!
Fixes #704
> Changing the OMO goal to custom

- src/ontology/ro-edit.owl
as per the comments by @matentzn and @anitacaron .
> Grammar fix in ro-edit.owl, as per #800

- src/ontology/components/core.owl
I did this before for ro-edit.owl (#776) but missed core.owl. Fixes #803.
> Rename SWRL variables to use valid URN format

- src/ontology/components/rohom.owl
- src/ontology/components/temporal-intervals.owl
FYI @anitacaron this is just from saving the ontology with Protege 5.6 - merging into the #852 branch
> Normalise rohom and temporal intervals
